INSERT INTO USERS (USER_ID, USERNAME, EMAIL, TOURS_TRAVELLED, TICKET_BOUGHT, WALLET)VALUES ('U001', 'john_doe', 'john.doe@example.com', 3, 5, 1500.75);
INSERT INTO USERS (USER_ID, USERNAME, EMAIL, TOURS_TRAVELLED, TICKET_BOUGHT, WALLET)VALUES ('U002', 'jane_smith', 'jane.smith@example.com', 7, 10, 3200.50);
INSERT INTO USERS (USER_ID, USERNAME, EMAIL, TOURS_TRAVELLED, TICKET_BOUGHT, WALLET)VALUES ('U003', 'alex_brown', 'alex.brown@example.com', 1, 2, 500.00);
INSERT INTO USERS (USER_ID, USERNAME, EMAIL, TOURS_TRAVELLED, TICKET_BOUGHT, WALLET)VALUES ('U004', 'emily_white', 'emily.white@example.com', 5, 8, 2100.25);
INSERT INTO USERS (USER_ID, USERNAME, EMAIL, TOURS_TRAVELLED, TICKET_BOUGHT, WALLET)VALUES ('U005', 'michael_lee', 'michael.lee@example.com', 0, 1, 250.00);
